### ISSUE TITLE
Reading Clipboard on Server

### ISSUE THREAD

**Issue by Fungusware** [Basaingeal/Razor.Clipboard#125]
On my local development machine I can read the clipboard without any issues when running inside Chrome, however once I publish to the server and again through Chrome I get the following error.

```
Microsoft.JSInterop.JSException: Cannot read property 'readText' of undefined
TypeError: Cannot read property 'readText' of undefined
    at Object.window.CurrieTechnologies.Razor.Clipboard.ReadText (http://tiger:8081/_content/CurrieTechnologies.Razor.Clipboard/clipboard.min.js:1:1286)
    at http://tiger:8081/_framework/blazor.server.js:8:31421
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://tiger:8081/_framework/blazor.server.js:8:31390)
    at http://tiger:8081/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://tiger:8081/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (http://tiger:8081/_framework/blazor.server.js:1:17165)
    at e.connection.onreceive (http://tiger:8081/_framework/blazor.server.js:1:10276)
    at e.<anonymous> (http://tiger:8081/_framework/blazor.server.js:1:30261)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at CurrieTechnologies.Razor.Clipboard.ClipboardService.ReadTextAsync()
   at BlazorExperiments.Pages.FollowUp.<BuildRenderTree>b__0_0(MouseEventArgs e) in C:\Development\GPT\NET\Websites\Experiments\BlazorExperiments\Pages\FollowUp.razor:line 33
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

Is there anything can be done about this, or something I am overlooking.

**Comment by Basaingeal** [comment]
I checked the latest version of the library on an Azure server, and it doesn't work any differently for me.
I might need more information. Is this a Blazor Server or Blazor WebAssembly app? Also, can you share the line of code that triggers this in your Blazor component? (.razor file)

**Comment by Fungusware** [comment]
Thanks for your response.

This is occuring in a Blazor Server app after it has been published to our local IIS server. I have not ried on Azure yet, but will do so as soon as I get the chance.

The line casuing the error is :

`
<button type="button" class="btn btn-primary" @onclick="(async e => ParseFollowUp(await clipboard.ReadTextAsync()))">Import from Clipboard</button>
`

Regards

**Comment by kunalbuxani** [comment]
I think we have the same problem. I'm using IsSupportedAsync(), and it's returning true in my local environment but false when I deploy to my IIS server. Haven't proved this with my application but I'm sure the problem is the clipboard API is only supported over HTTPS: https://developers.google.com/web/updates/2018/03/clipboardapi

**Comment by Basaingeal** [comment]
Thanks @kunalbuxani. That's almost certainly the problem. I forgot about that aspect of the Clipboard API. I tend to always be on an HTTPS connection.

I'll do some tests of my own, and then add a note to the readme about it. I'll probably need to include a link to Clipboard API documentation, because a few of the issues raised on this library seem to just be base browser behavior.

I'm glad that `IsSupportedAsync()` can pick up on it though.

**Comment by Basaingeal** [comment]
I've added some notes to the README concerning this and other situations that have come up. I've also included the article @kunalbuxani linked here, and the MDN documentation.

I haven't heard from the OP @Fungusware  in a while, so I will close this issue, and reopen if they find the problem is unrelated.

**Comment by Fungusware** [comment]
Thanks for all the effort on this, I didn't have much time to follow up but
do appreciate the efforts.
